### ISSUE TITLE
Update package.json after release

### ISSUE THREAD

**Issue by ClemMakesApps** [semantic-release/gitlab-config#31]
It would be nice to add a configuration to this so that developers have the option of having package.json version numbers automatically updated after each semantic-release.

It looks like https://github.com/semantic-release/git already offers this functionality, so it seems like all we have to do is bundle that into this config and be configurable through some environment variables

**Comment by pvdlg** [comment]
See semantic-release/semantic-release#827 that plans to create more shareable configs.

That said, the goal of shareable configs is to be a simple static config file (JSON). So we won't create shareable config that are themselves configurable (via environment variable or other).
If you don't find a config that fit your needs, then creates your own, it takes less than 5 minutes, it's 10 lines of JSON.

All the `@semantic-release/**-config` repo are there to cover basic common needs and to demonstrate how to create a shareable config. The goal is not for us to have a config for each possible combination. The goal is for users to create their own.

**Comment by ClemMakesApps** [comment]
Gotcha, thanks for explaining it @pvdlg! That was very helpful.
