### ISSUE TITLE
An error occurred while running semantic-release: SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by egemon** [semantic-release/gitlab-config#325]
Probably caused by node_modules/@semantic-release/gitlab/lib/definitions/errors.js

`import pkg from '../../package.json' assert {type: 'json'};`

Probably can be dropped?

**Comment by egemon** [comment]
Caused by https://github.com/nodejs/node/pull/52104

**Comment by fgreinacher** [comment]
This is already fixed in https://github.com/semantic-release/gitlab/pull/708. Please update your lockfile and it will reach the config preset.
